//! Render an aggregated view as Markdown.

use std::fmt::Write as _;

use crate::aggregate::{AggregatedView, LeaderboardRow};

/// Build the full `LEADERBOARD.md` body.
pub fn render(view: &AggregatedView) -> String {
    let mut s = String::with_capacity(2048);
    let _ = writeln!(&mut s, "# Rupert Leaderboard");
    let _ = writeln!(&mut s);
    let _ = writeln!(&mut s, "Generated by `rupert lead build`. Each row aggregates all seeds for one (shape, solver) pair; the headline is the best certified result.");
    let _ = writeln!(&mut s);
    let _ = writeln!(&mut s, "## Headline");
    let _ = writeln!(&mut s);
    if view.headline.is_empty() {
        let _ = writeln!(&mut s, "_No certified passages yet._");
    } else {
        render_table(&mut s, &view.headline);
    }
    let _ = writeln!(&mut s);
    let _ = writeln!(&mut s, "## Uncertified candidates");
    let _ = writeln!(&mut s);
    if view.uncertified.is_empty() {
        let _ = writeln!(&mut s, "_None._");
    } else {
        render_table(&mut s, &view.uncertified);
    }
    let _ = writeln!(&mut s);
    let _ = writeln!(&mut s, "## Open problems");
    let _ = writeln!(&mut s);
    if view.open_problems.is_empty() {
        let _ = writeln!(&mut s, "_All shapes have at least one certified passage._");
    } else {
        for shape in &view.open_problems {
            let _ = writeln!(&mut s, "- `{shape}`");
        }
    }
    s
}

fn render_table(s: &mut String, rows: &[LeaderboardRow]) {
    let _ = writeln!(s, "| shape | solver | best evals | clearance | best seed | wall ms | samples |");
    let _ = writeln!(s, "|-------|--------|-----------:|----------:|----------:|--------:|--------:|");
    let mut sorted: Vec<&LeaderboardRow> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        a.shape
            .cmp(&b.shape)
            .then_with(|| a.best_eval_count.cmp(&b.best_eval_count))
    });
    for r in sorted {
        let _ = writeln!(
            s,
            "| `{}` | `{}` v{} | {} | {:.6e} | {} | {} | {} |",
            r.shape,
            r.solver,
            r.solver_version,
            r.best_eval_count,
            r.best_clearance,
            r.best_seed,
            r.wall_time_ms,
            r.samples
        );
    }
}

#[cfg(test)]
mod tests {
    use crate::aggregate::AggregatedView;

    use super::*;

    #[test]
    fn empty_view_has_three_sections() {
        let s = render(&AggregatedView::default());
        assert!(s.contains("## Headline"));
        assert!(s.contains("## Uncertified candidates"));
        assert!(s.contains("## Open problems"));
    }

    #[test]
    fn headline_row_appears_in_output() {
        let mut view = AggregatedView::default();
        view.headline.push(LeaderboardRow {
            shape: "cube".into(),
            solver: "test".into(),
            solver_version: "0.1.0".into(),
            best_seed: 0,
            best_eval_count: 42,
            best_clearance: 0.123,
            wall_time_ms: 5,
            samples: 1,
        });
        let s = render(&view);
        assert!(s.contains("`cube`"));
        assert!(s.contains("42"));
        assert!(s.contains("0.1.0"));
    }
}
