//! Render an aggregated view as Markdown.

use std::fmt::Write as _;

use crate::aggregate::{AggregatedView, LeaderboardRow};

#[derive(Debug, Clone, Copy)]
enum SortBy {
    EvalsAsc,
    ClearanceDesc,
}

/// Build the full `LEADERBOARD.md` body.
pub fn render(view: &AggregatedView) -> String {
    let mut s = String::with_capacity(4096);
    let _ = writeln!(&mut s, "# Rupert Leaderboard");
    let _ = writeln!(&mut s);
    let _ = writeln!(
        &mut s,
        "Generated by `rupert lead build`. Each row aggregates all seeds for one (shape, solver) pair. **Headline** ranks by fastest passage (smallest eval count); **Highest clearance** ranks by largest clearance margin (refiner-friendly); **Open best observations** ranks exhausted runs by `best_near_miss`, so boundary contacts do not dominate open targets."
    );
    let _ = writeln!(&mut s);

    let _ = writeln!(&mut s, "## Headline (fastest passage)");
    let _ = writeln!(&mut s);
    if view.headline.is_empty() {
        let _ = writeln!(&mut s, "_No certified passages yet._");
    } else {
        render_table(&mut s, &view.headline, SortBy::EvalsAsc);
    }
    let _ = writeln!(&mut s);

    let _ = writeln!(&mut s, "## Highest clearance");
    let _ = writeln!(&mut s);
    if view.highest_clearance.is_empty() {
        let _ = writeln!(&mut s, "_No certified passages yet._");
    } else {
        render_table(&mut s, &view.highest_clearance, SortBy::ClearanceDesc);
    }
    let _ = writeln!(&mut s);

    let _ = writeln!(&mut s, "## Uncertified candidates");
    let _ = writeln!(&mut s);
    if view.uncertified.is_empty() {
        let _ = writeln!(&mut s, "_None._");
    } else {
        render_table(&mut s, &view.uncertified, SortBy::EvalsAsc);
    }
    let _ = writeln!(&mut s);

    let _ = writeln!(&mut s, "## Open best observations");
    let _ = writeln!(&mut s);
    if view.open_observations.is_empty() {
        let _ = writeln!(&mut s, "_No exhausted-run observations yet._");
    } else {
        render_table(&mut s, &view.open_observations, SortBy::ClearanceDesc);
    }
    let _ = writeln!(&mut s);

    let _ = writeln!(&mut s, "## Open problems");
    let _ = writeln!(&mut s);
    if view.open_problems.is_empty() {
        let _ = writeln!(&mut s, "_All shapes have at least one certified passage._");
    } else {
        for shape in &view.open_problems {
            let _ = writeln!(&mut s, "- `{shape}`");
        }
    }
    s
}

fn render_table(s: &mut String, rows: &[LeaderboardRow], sort_by: SortBy) {
    let _ = writeln!(
        s,
        "| shape | solver | cert | best evals | clearance | best seed | wall ms | samples |"
    );
    let _ = writeln!(
        s,
        "|-------|--------|------|-----------:|----------:|----------:|--------:|--------:|"
    );
    let mut sorted: Vec<&LeaderboardRow> = rows.iter().collect();
    sorted.sort_by(|a, b| {
        let primary = a.shape.cmp(&b.shape);
        match sort_by {
            SortBy::EvalsAsc => primary.then_with(|| a.best_eval_count.cmp(&b.best_eval_count)),
            SortBy::ClearanceDesc => primary.then_with(|| {
                b.best_clearance
                    .partial_cmp(&a.best_clearance)
                    .unwrap_or(std::cmp::Ordering::Equal)
            }),
        }
    });
    for r in sorted {
        let cert_label = match r.cert_method {
            Some(rupert_core::CertMethod::ExactRational) => "exact",
            Some(rupert_core::CertMethod::IntervalSnap) => "interval",
            Some(rupert_core::CertMethod::F64Epsilon) => "f64ε",
            None => "—",
        };
        let _ = writeln!(
            s,
            "| `{}` | `{}` v{} | {} | {} | {:.6e} | {} | {} | {} |",
            r.shape,
            r.solver,
            r.solver_version,
            cert_label,
            r.best_eval_count,
            r.best_clearance,
            r.best_seed,
            r.wall_time_ms,
            r.samples
        );
    }
}

#[cfg(test)]
mod tests {
    use crate::aggregate::AggregatedView;

    use super::*;

    #[test]
    fn empty_view_has_sections() {
        let s = render(&AggregatedView::default());
        assert!(s.contains("## Headline"));
        assert!(s.contains("## Highest clearance"));
        assert!(s.contains("## Uncertified candidates"));
        assert!(s.contains("## Open best observations"));
        assert!(s.contains("## Open problems"));
    }

    #[test]
    fn headline_row_appears_in_output() {
        let mut view = AggregatedView::default();
        view.headline.push(LeaderboardRow {
            shape: "cube".into(),
            solver: "test".into(),
            solver_version: "0.1.0".into(),
            best_seed: 0,
            best_eval_count: 42,
            best_clearance: 0.123,
            wall_time_ms: 5,
            samples: 1,
            cert_method: Some(rupert_core::CertMethod::F64Epsilon),
        });
        let s = render(&view);
        assert!(s.contains("`cube`"));
        assert!(s.contains("42"));
        assert!(s.contains("0.1.0"));
    }

    #[test]
    fn highest_clearance_section_renders_independently() {
        let mut view = AggregatedView::default();
        view.highest_clearance.push(LeaderboardRow {
            shape: "cube".into(),
            solver: "imperts".into(),
            solver_version: "0.2.0".into(),
            best_seed: 7,
            best_eval_count: 50_000,
            best_clearance: 0.0875,
            wall_time_ms: 23,
            samples: 3,
            cert_method: Some(rupert_core::CertMethod::IntervalSnap),
        });
        let s = render(&view);
        let highest_idx = s.find("## Highest clearance").expect("section");
        // The imperts row should appear AFTER the heading.
        let after = &s[highest_idx..];
        assert!(after.contains("imperts"));
        assert!(after.contains("0.2.0"));
    }
}
